source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'

target 'UnityFramework' do
  pod 'ARCore/GARSession', '~> 1.37.0'
  pod 'ARCore/Geospatial', '~> 1.37.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
